### ISSUE TITLE
SADL scoping issues - Umbrella task for multiple scoping issues.

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#256]
Just to have one PR for all scoping related tasks.

 - [x] [Rule Variable Definition correct for SubjHasProp but not for PropOfSubject](https://github.com/crapo/sadlos2/issues/245)
 - [x] [Built-in function arguments are exported to the global scope](https://github.com/crapo/sadlos2/issues/249)
 - [x] [Scoping issue with embedded instance](https://github.com/crapo/sadlos2/issues/250)

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/257
